#!/bin/bash

CORE="0"
PROGRAM="matmult"
echo Profiling program $PROGRAM on core $CORE

echo ================================================================================
echo

for i in FLOPS_DP L2 L2CACHE
do
	echo Measuring performance for event group $i \
	     using the marker api...

        likwid-perfctr -C $CORE -g $i -m ./$PROGRAM A2.in B2.in new.out

	echo ================================================================================
	echo
done
