#!/bin/bash

clear
make clean
make

CORE="2"
PROGRAM="matmult"
echo Profiling program $PROGRAM on core $CORE

echo ================================================================================
echo

for i in FLOPS_DP L2 L2CACHE
do
	echo Measuring performance for event group $i \
	     using the marker api...

        likwid-perfctr -C $CORE -g $i -m ./$PROGRAM 2048*2048-1 2048*2048-2 new.out

	echo ================================================================================
	echo
done
